// Demo-alert seed (SEED-002).
//
// Creates a deterministic set of pre-built alerts covering all five
// classification types (aligned, drifted, contradicted, ambiguous,
// no_material_impact) drawn from the real regulatory cache in
// data/regulatory/<src>/cache.json matched against the dummy policy corpus
// seeded by SEED-001.
//
// Idempotency is achieved with stable IDs (`seed-demo-alerts-*`); re-running
// deletes the prior demo run + items + alerts + audit entries before
// recreating them, so the seed can be run repeatedly without accumulating
// duplicates.

import type { Client } from "@libsql/client";

export const DEMO_RUN_ID = "seed-demo-alerts-run-001";
const REG_ID_PREFIX = "seed-demo-alerts-reg-";
const ALERT_ID_PREFIX = "seed-demo-alerts-alt-";
const AUDIT_ID_PREFIX = "seed-demo-alerts-aud-";

type DemoAlertFixture = {
  reg: {
    sourceUrl: string;
    regulator: "SEC" | "FINRA" | "CFPB" | "OCC";
    publicationDate: string;
    documentType: string;
    title: string;
    fullText: string;
  };
  policy: {
    domain: string;
    sectionHeading: string;
  };
  classification:
    | "aligned"
    | "drifted"
    | "contradicted"
    | "ambiguous"
    | "no_material_impact";
  confidence: number;
  severity: "high" | "medium" | "low";
  explanation: string;
  regulatoryQuote: string;
  policyQuote: string;
  // Days before "now" to backdate createdAt so the demo alerts spread across
  // a realistic timeline rather than all clustering at this very second.
  daysAgo: number;
};

const FIXTURES: DemoAlertFixture[] = [
  {
    reg: {
      sourceUrl: "https://www.sec.gov/news/press-release/2025-014",
      regulator: "SEC",
      publicationDate: "2025-01-22T14:30:00Z",
      documentType: "press_release",
      title:
        "SEC Charges Investment Adviser With Failing to Address AI Disclosure Controls",
      fullText:
        "The Securities and Exchange Commission today charged a registered investment adviser with failing to implement reasonably designed compliance policies and procedures concerning the firm's use of artificial intelligence in its investment process. According to the order, the adviser publicly represented that its investment recommendations were generated by proprietary AI models, but failed to maintain documentation of model training data, validation protocols, or performance monitoring. The order finds that this conduct violated Section 206(4) of the Investment Advisers Act of 1940 and Rule 206(4)-7 thereunder. Without admitting or denying the findings, the firm agreed to a cease-and-desist order, censure, a $400,000 civil penalty, and undertakings to enhance its AI governance program.",
    },
    policy: { domain: "marketing", sectionHeading: "5. Pre-Publication Review Workflow" },
    classification: "drifted",
    confidence: 0.85,
    severity: "medium",
    explanation:
      "The SEC enforcement action signals that registered firms must document AI model training data, validation protocols, and performance monitoring. The Bank's pre-publication review workflow describes a generic disclosure / prominence checklist but is silent on AI-generated content, AI-driven recommendations, and supporting documentation requirements — leaving a gap between current expectations and the policy as written.",
    regulatoryQuote:
      "failed to maintain documentation of model training data, validation protocols, or performance monitoring",
    policyQuote:
      "the Marketing Compliance Liaison runs the Bank's product/channel checklist for required disclosures, prominence, and contact information",
    daysAgo: 14,
  },
  {
    reg: {
      sourceUrl: "https://www.finra.org/rules-guidance/notices/25-04",
      regulator: "FINRA",
      publicationDate: "2025-02-10T13:30:00Z",
      documentType: "regulatory_notice",
      title:
        "FINRA Provides Guidance on Use of Generative Artificial Intelligence in Member Firm Operations",
      fullText:
        "This Regulatory Notice provides guidance to member firms regarding the use of generative artificial intelligence and large language models in connection with broker-dealer activities. Firms remain responsible for compliance with all applicable FINRA rules, including supervision (Rule 3110), communications with the public (Rule 2210), customer information protection (Reg S-P), and books and records requirements (Rule 4511). Firms using generative AI tools to draft customer communications, summarize research, or assist registered representatives must establish written supervisory procedures addressing model selection, output review, recordkeeping of prompts and outputs, and testing for accuracy and bias. Firms are reminded that any communications generated or substantially modified by AI that are distributed to customers constitute communications with the public subject to principal approval and filing requirements where applicable.",
    },
    policy: {
      domain: "vendor_management",
      sectionHeading: "5. Risk Assessment and Tiering",
    },
    classification: "drifted",
    confidence: 0.62,
    severity: "low",
    explanation:
      "FINRA expects firms to apply written supervisory procedures specifically to generative-AI vendors, including model selection, output review, and prompt/output recordkeeping. The Bank's vendor risk-tiering process enumerates traditional risk factors (strategic purpose, criticality, NPI access) but does not yet incorporate AI-specific risk dimensions; the gap is moderate but actionable.",
    regulatoryQuote:
      "must establish written supervisory procedures addressing model selection, output review, recordkeeping of prompts and outputs, and testing for accuracy and bias",
    policyQuote:
      "the Business Owner, with TPRMO oversight, performs a risk assessment considering, at a minimum: strategic purpose; nature and volume of the activity; whether the activity is critical",
    daysAgo: 22,
  },
  {
    reg: {
      sourceUrl:
        "https://www.consumerfinance.gov/about-us/newsroom/cfpb-finalizes-overdraft-rule-large-banks/",
      regulator: "CFPB",
      publicationDate: "2025-03-05T13:30:00Z",
      documentType: "publication",
      title:
        "CFPB Finalizes Rule on Overdraft Fees Charged by Very Large Financial Institutions",
      fullText:
        "The Consumer Financial Protection Bureau today finalized a rule limiting overdraft fees charged by very large financial institutions, defined as banks and credit unions with more than $10 billion in assets. The final rule treats overdraft credit as consumer credit subject to the Truth in Lending Act and Regulation Z when an institution charges fees in excess of a benchmark amount. Covered institutions must provide consumers with disclosures, including the cost of credit expressed as an annual percentage rate, and must comply with TILA's substantive protections. The rule preserves three options for covered institutions: charge a courtesy fee at or below the benchmark, charge a fee that recovers the institution's costs and losses with documentation, or treat the overdraft service as a covered credit product subject to TILA. Institutions must update consumer disclosures, deposit account agreements, and supervisory procedures to reflect the rule's effective date. The Bureau notes that institutions remain subject to UDAAP and Regulation E protections regardless of which option they elect.",
    },
    policy: { domain: "overdraft", sectionHeading: "8. Fee Structure and Limits" },
    classification: "contradicted",
    confidence: 0.91,
    severity: "high",
    explanation:
      "The new CFPB rule treats overdraft fees above a benchmark as consumer credit subject to TILA / Regulation Z and requires APR disclosure plus the three structural options (courtesy fee at-or-below benchmark, cost-justified fee with documentation, or treat as TILA credit). The Bank's overdraft fee schedule charges a flat $35 per item without TILA classification, benchmark testing, or APR disclosure — directly contradicted by the finalized rule.",
    regulatoryQuote:
      "charge a courtesy fee at or below the benchmark, charge a fee that recovers the institution's costs and losses with documentation, or treat the overdraft service as a covered credit product subject to TILA",
    policyQuote:
      "$35 per item paid into overdraft, subject to the limits in this Section",
    daysAgo: 5,
  },
  {
    reg: {
      sourceUrl:
        "https://www.consumerfinance.gov/about-us/newsroom/cfpb-issues-circular-on-fair-lending-marketing-practices/",
      regulator: "CFPB",
      publicationDate: "2025-02-18T15:00:00Z",
      documentType: "publication",
      title:
        "CFPB Issues Circular on Fair Lending Implications of Targeted Marketing Practices",
      fullText:
        "The Consumer Financial Protection Bureau today issued a circular addressing the fair lending implications of targeted marketing and advertising practices used by financial institutions. The circular reaffirms that the Equal Credit Opportunity Act and Regulation B prohibit creditors from discriminating in any aspect of a credit transaction on a prohibited basis, including through digital advertising tools that may steer or limit access to credit offers based on protected characteristics. Creditors are reminded that they remain responsible for compliance when they use third-party platforms or algorithmic targeting tools, and that they must implement reasonable policies and procedures to monitor advertising audience composition and outcomes. The circular outlines record retention obligations under Regulation B for prescreened solicitations and digital marketing campaigns, and warns that failure to monitor disparate impact in marketing audiences may constitute a violation of ECOA. Institutions are urged to review their fair lending compliance management systems, consumer compliance training, and complaint-monitoring procedures in light of this guidance.",
    },
    policy: { domain: "fair_lending", sectionHeading: "5. Marketing and Outreach" },
    classification: "contradicted",
    confidence: 0.65,
    severity: "medium",
    explanation:
      "CFPB Circular reaffirms that creditors must monitor advertising audience composition and outcomes when using third-party platforms or algorithmic targeting tools, and treats failure to do so as a possible ECOA violation. The Bank's marketing-and-outreach section requires Fair Lending Officer review of pre-screening criteria before launch and annually thereafter, but does not require ongoing audience-composition monitoring of digital and algorithmic ad platforms in between — the circular's explicit expectation runs against the policy's narrower review cadence.",
    regulatoryQuote:
      "they must implement reasonable policies and procedures to monitor advertising audience composition and outcomes",
    policyQuote:
      "Pre-screening criteria used for solicitations are reviewed by the Fair Lending Officer before launch and at least annually thereafter",
    daysAgo: 19,
  },
  {
    reg: {
      sourceUrl: "https://www.occ.gov/news-issuances/bulletins/2025/bulletin-2025-3.html",
      regulator: "OCC",
      publicationDate: "2025-02-12T14:00:00Z",
      documentType: "bulletin",
      title:
        "OCC Bulletin 2025-3: Bank Secrecy Act / Anti-Money Laundering Examination Priorities",
      fullText:
        "The Office of the Comptroller of the Currency today issued a bulletin reaffirming Bank Secrecy Act and anti-money laundering supervisory priorities for national banks, federal savings associations, and federal branches and agencies of foreign banks. The bulletin emphasizes that examiners will focus on the adequacy of customer due diligence and beneficial ownership identification programs, the timeliness and quality of suspicious activity report filings, the integrity of currency transaction reporting, and the effectiveness of the institution's risk-based BSA compliance program. Banks are reminded that BSA officers must have sufficient authority, resources, and independence to administer the program, and that the board of directors must receive regular reporting on BSA/AML risk and program effectiveness. The bulletin also addresses heightened expectations for monitoring of higher-risk customer relationships, including money services businesses, private banking customers, and politically exposed persons. Institutions should review their independent testing scope and frequency to ensure ongoing alignment with the institution's risk profile and recent regulatory guidance from FinCEN.",
    },
    policy: { domain: "bsa_aml", sectionHeading: "5. Risk Assessment" },
    classification: "ambiguous",
    confidence: 0.55,
    severity: "low",
    explanation:
      "The OCC bulletin lists supervisory priorities at a general level and points to ongoing FinCEN guidance for specifics, without setting numeric or testable thresholds. The Bank's risk-assessment section already contemplates higher-risk relationships and independent-testing alignment but it is unclear whether the bulletin's call to 'review independent testing scope and frequency' reaches beyond the existing annual cycle. The mismatch is real but its magnitude depends on supervisory interpretation.",
    regulatoryQuote:
      "Institutions should review their independent testing scope and frequency to ensure ongoing alignment with the institution's risk profile and recent regulatory guidance from FinCEN",
    policyQuote:
      "The Bank maintains a written enterprise BSA/AML risk assessment that is refreshed at least annually, or upon any material change to products, customers, geographies, services, or regulatory expectations",
    daysAgo: 26,
  },
  {
    reg: {
      sourceUrl: "https://www.finra.org/rules-guidance/notices/25-01",
      regulator: "FINRA",
      publicationDate: "2025-01-15T14:00:00Z",
      documentType: "regulatory_notice",
      title:
        "FINRA Reminds Member Firms of Their Obligations Regarding Customer Complaint Reporting",
      fullText:
        "FINRA reminds member firms of their obligations under FINRA Rule 4530 to report customer complaints and certain disciplinary information promptly. The notice clarifies that complaints alleging theft, misappropriation of funds or securities, or forgery must be reported within 30 calendar days of receipt. Firms must establish written supervisory procedures reasonably designed to capture, track, and escalate customer complaints, including complaints received through digital channels such as social media, mobile applications, and chat features. The notice also addresses recordkeeping obligations under Rule 4511 and SEC Rule 17a-4 for retaining complaint correspondence. Firms that fail to maintain adequate complaint-intake systems or fail to report qualifying complaints within the prescribed timeframes may be subject to disciplinary action.",
    },
    policy: { domain: "complaint_handling", sectionHeading: "10. Reporting" },
    classification: "aligned",
    confidence: 0.92,
    severity: "low",
    explanation:
      "FINRA reaffirms existing Rule 4530 reporting timeframes (30 calendar days for theft/misappropriation/forgery complaints) and the requirement to capture digital-channel complaints. The Bank's complaint-handling reporting section already mirrors these timeframes and explicitly enumerates digital channels (social media, mobile applications, chat) as in-scope. The policy is materially aligned with the notice; no remediation indicated.",
    regulatoryQuote:
      "complaints alleging theft, misappropriation of funds or securities, or forgery must be reported within 30 calendar days of receipt",
    policyQuote:
      "A monthly Regulatory Complaint Report identifying every CFPB Consumer Response matter and every state regulator complaint, with status and aging",
    daysAgo: 30,
  },
  {
    reg: {
      sourceUrl: "https://www.sec.gov/news/press-release/2025-001",
      regulator: "SEC",
      publicationDate: "2025-01-08T15:00:00Z",
      documentType: "press_release",
      title: "SEC Announces Enforcement Results for Fiscal Year 2024",
      fullText:
        "The Securities and Exchange Commission today announced that it filed 583 total enforcement actions in fiscal year 2024 and obtained orders for $8.2 billion in financial remedies, the highest amount in SEC history. The Commission also obtained orders barring 124 individuals from serving as officers and directors of public companies. The enforcement program prioritized investor protection, market integrity, and accountability for individuals. Cases addressed misconduct involving accounting fraud, market manipulation, insider trading, custody and recordkeeping violations by registrants, and abuses of emerging technologies including AI-washing and crypto asset fraud. The Division also pursued more than 200 actions for off-channel communications recordkeeping failures by broker-dealers and investment advisers.",
    },
    policy: { domain: "bsa_aml", sectionHeading: "16. Compliance Monitoring" },
    classification: "no_material_impact",
    confidence: 0.78,
    severity: "low",
    explanation:
      "The SEC enforcement-results press release reports aggregate fiscal-year statistics and does not establish, modify, or interpret a substantive obligation that would intersect with the Bank's BSA/AML compliance-monitoring program. The publication is informational in nature and does not require any change to the Bank's monitoring scope, frequency, or escalation thresholds.",
    regulatoryQuote:
      "filed 583 total enforcement actions in fiscal year 2024 and obtained orders for $8.2 billion in financial remedies, the highest amount in SEC history",
    policyQuote:
      "The Financial Crimes Compliance team performs ongoing quality assurance over alert disposition, SAR narratives, CTR accuracy, and CDD refresh timeliness",
    daysAgo: 35,
  },
];

export type SeedDemoAlertsResult = {
  runId: string;
  alertIds: string[];
  regulatoryItemIds: string[];
};

export async function seedDemoAlerts(client: Client): Promise<SeedDemoAlertsResult> {
  // 1. Wipe any prior demo seed run (audit -> alerts -> reg items -> run).
  await client.execute({
    sql: `DELETE FROM AuditEntry WHERE id LIKE ?`,
    args: [`${AUDIT_ID_PREFIX}%`],
  });
  await client.execute({
    sql: `DELETE FROM Alert WHERE id LIKE ?`,
    args: [`${ALERT_ID_PREFIX}%`],
  });
  await client.execute({
    sql: `DELETE FROM RegulatoryItem WHERE id LIKE ?`,
    args: [`${REG_ID_PREFIX}%`],
  });
  await client.execute({
    sql: `DELETE FROM IngestionRun WHERE id = ?`,
    args: [DEMO_RUN_ID],
  });

  // 2. Resolve a PolicyChunk id for each fixture's (domain, sectionHeading)
  // pair. The chunks were just inserted by the policy seed in this same run.
  const chunkIds: string[] = [];
  for (const fix of FIXTURES) {
    const result = await client.execute({
      sql: `SELECT pc.id AS chunkId
              FROM PolicyChunk pc
              JOIN PolicyDocument pd ON pd.id = pc.policyDocumentId
             WHERE pd.domain = ? AND pc.sectionHeading = ?
             LIMIT 1`,
      args: [fix.policy.domain, fix.policy.sectionHeading],
    });
    const row = result.rows[0];
    if (!row) {
      throw new Error(
        `seedDemoAlerts: no PolicyChunk found for domain=${fix.policy.domain} section="${fix.policy.sectionHeading}". Was the policy corpus seeded?`,
      );
    }
    chunkIds.push(String(row.chunkId));
  }

  // 3. Create the demo IngestionRun.
  const now = new Date();
  const nowIso = now.toISOString();
  // Spread RegulatoryItem.publicationDate values aren't enough; we want the
  // run itself dated so the dashboard's "recent runs" widget shows the seed.
  await client.execute({
    sql: `INSERT INTO IngestionRun (id, trigger, status, startedAt, completedAt, itemsProcessed, itemsFlagged, itemsSuppressed)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      DEMO_RUN_ID,
      "manual",
      "completed",
      nowIso,
      nowIso,
      FIXTURES.length,
      FIXTURES.length,
      0,
    ],
  });

  // 4. Insert RegulatoryItem + Alert + AuditEntry triplets for each fixture.
  const alertIds: string[] = [];
  const regulatoryItemIds: string[] = [];
  for (let i = 0; i < FIXTURES.length; i++) {
    const fix = FIXTURES[i]!;
    const regId = `${REG_ID_PREFIX}${String(i + 1).padStart(3, "0")}`;
    const alertId = `${ALERT_ID_PREFIX}${String(i + 1).padStart(3, "0")}`;
    const auditId = `${AUDIT_ID_PREFIX}${String(i + 1).padStart(3, "0")}`;
    const createdAt = new Date(now.getTime() - fix.daysAgo * 86_400_000);
    const createdAtIso = createdAt.toISOString();
    const policyReference = await resolvePolicyReference(
      client,
      fix.policy.domain,
      fix.policy.sectionHeading,
    );

    await client.execute({
      sql: `INSERT INTO RegulatoryItem (id, sourceUrl, regulator, publicationDate, documentType, title, fullText, summary, isRelevant, ingestionRunId, createdAt, updatedAt)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        regId,
        fix.reg.sourceUrl,
        fix.reg.regulator,
        new Date(fix.reg.publicationDate).toISOString(),
        fix.reg.documentType,
        fix.reg.title,
        fix.reg.fullText,
        null,
        1,
        DEMO_RUN_ID,
        createdAtIso,
        createdAtIso,
      ],
    });

    await client.execute({
      sql: `INSERT INTO Alert (id, regulatoryItemId, policyChunkId, classification, confidence, severity, explanation, regulatoryQuote, policyQuote, regulatorySourceUrl, policyReference, status, createdAt, updatedAt)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        alertId,
        regId,
        chunkIds[i]!,
        fix.classification,
        fix.confidence,
        fix.severity,
        fix.explanation,
        fix.regulatoryQuote,
        fix.policyQuote,
        fix.reg.sourceUrl,
        policyReference,
        "open",
        createdAtIso,
        createdAtIso,
      ],
    });

    await client.execute({
      sql: `INSERT INTO AuditEntry (id, alertId, actor, action, beforeState, afterState, note, timestamp)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
      args: [
        auditId,
        alertId,
        "system",
        "created",
        null,
        null,
        null,
        createdAtIso,
      ],
    });

    alertIds.push(alertId);
    regulatoryItemIds.push(regId);
  }

  return { runId: DEMO_RUN_ID, alertIds, regulatoryItemIds };
}

async function resolvePolicyReference(
  client: Client,
  domain: string,
  sectionHeading: string,
): Promise<string> {
  const result = await client.execute({
    sql: `SELECT pd.title AS policyTitle
            FROM PolicyChunk pc
            JOIN PolicyDocument pd ON pd.id = pc.policyDocumentId
           WHERE pd.domain = ? AND pc.sectionHeading = ?
           LIMIT 1`,
    args: [domain, sectionHeading],
  });
  const row = result.rows[0];
  if (!row) {
    throw new Error(
      `resolvePolicyReference: no PolicyChunk for domain=${domain} section="${sectionHeading}"`,
    );
  }
  return `${String(row.policyTitle)} > ${sectionHeading}`;
}
